// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI.Models;

#nullable disable

namespace TravelAPI.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    [Migration("20230814171947_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelAPI.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("longtext");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            CityName = "Bend",
                            Country = "United States",
                            Rating = 9,
                            Review = "Nice sunny vaction spot"
                        },
                        new
                        {
                            DestinationId = 2,
                            CityName = "Sayulita",
                            Country = "Mexico",
                            Rating = 8,
                            Review = "Surf vacation spot"
                        },
                        new
                        {
                            DestinationId = 3,
                            CityName = "Osaka",
                            Country = "Japan",
                            Rating = 10,
                            Review = "Great place to see Japanese food spots and culture"
                        },
                        new
                        {
                            DestinationId = 4,
                            CityName = "Alicante",
                            Country = "Spain",
                            Rating = 8,
                            Review = "Good food and great flamenco"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
